Repository 0xPolygonZero/zero-bin, pull requests merged in 2024-03, with the labels that each got.

#24 Add test tooling for easier block / txn debugging
  Cargo.lock
  Cargo.toml
  leader/Cargo.toml
  ops/Cargo.toml
  ops/src/lib.rs
  prover/Cargo.toml
  prover/src/lib.rs
  rpc/Cargo.toml
  tools/debug_block.sh
  tools/prove_blocks.sh
Labels: enhancement

#29 Fix checkpoint block for debugging script
  tools/debug_block.sh
  tools/prove_blocks.sh
Labels: bug

#39 Fix dead link to prover_input.rs in README
  README.md
Labels: documentation
